const data = {
  products: [
    {
      name: "Nike Slim cap",
      slug: "nike-slim-cap",
      category: "Caps",
      image: "/images/p1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality cap",
    },
    {
      name: "Adidas Fit cap",
      slug: "adidas-fit-cap",
      category: "Caps",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Slim Cap",
      slug: "adidas-slim-cap",
      category: "Caps",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Nike Fit Cap",
      slug: "nike-fit-cap",
      category: "Caps",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Puma Slim cap",
      slug: "puma-slim-cap",
      category: "Caps",
      image: "/images/p5.jpg", 
      price: 120,
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality cap",
    },
    {
      name: "Puma Fit cap",
      slug: "puma-fit-cap",
      category: "Caps",
      image: "/images/p6.jpg",
      price: 250,
      countInStock: 20,
      brand: "Puma",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
